config/routes.rb
Rails.application.routes.draw do
  resources :schedules do
    collection do
      post :recalculate
      get :sum
    end
  end
  resources :custom_holidays
  root to: 'schedules#index'
  resources :meals do
    collection do
      post :import
    end
  end
  namespace 'api', format: 'json' do
    namespace 'v1' do
      resources :schedules do
        collection do
          get :index
        end
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :meal

  def self.sum_foods(schedules)
    foods = {}
    schedules.each do |schedule|
      schedule.meal.meal_foods.each do |mf|
        foods[mf.food.name] = [] unless foods.key?(mf.food.name) # 食材がキーに存在しなければ空の配列を作成
        foods[mf.food.name] << mf.amount # 同じ食材を配列へ
      end
    end
    foods
  end
end

app/controllers/api/v1/schedules_controller.rb
module Api
  module V1
    class SchedulesController < ApplicationController
      def index
        schedules = Schedule.includes(meal: :foods).where(date: [Date.today..(Date.today + 2)])
        meals = schedules.map do |schedule|
          { date: schedule.date, text: "#{schedule.meal.ordinal_number}回食(#{schedule.meal.meal_foods.map do |mf|
                                                                              "#{mf.food.name}#{mf.amount}"
                                                                            end.join(' ')})" }
        end
        respond_to do |format|
          format.json { render json: { title: '離乳食', meals: }, status: :ok }
        end
      end
    end
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: %i[show edit update destroy]

  # GET /schedules or /schedules.json
  def index
    set_date_range
    @schedules = Schedule.includes(meal: :foods).where(date: [@from..@to])
  end

  # GET /schedules/1 or /schedules/1.json
  def show; end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit; end

  # POST /schedules or /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to schedule_url(@schedule), notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1 or /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to schedule_url(@schedule), notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1 or /schedules/1.json
  def destroy
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /schedules/recalculate
  def recalculate
    respond_to do |format|
      if RecalculateSchedule.call(day: params[:day], start_date: params[:start_date])
        format.html { redirect_to schedules_url, notice: 'スケジュールの再計算が完了しました' }
      else
        format.html { redirect_to schedules_url, alert: 'スケジュールの再計算が失敗しました' }
      end
      format.json { head :no_content }
    end
  end

  def sum
    set_date_range
    @schedules = Schedule.includes(meal: :foods).where(date: [@from..@to])
    @foods = Schedule.sum_foods(@schedules)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_schedule
    @schedule = Schedule.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def schedule_params
    params.require(:schedule).permit(:date)
  end

  def set_date_range
    # デフォルト：今日を含めた7日間のスケジュールを表示
    @from =
      if params[:from].nil? || params[:from].empty?
        Date.today
      else
        Date.parse(params[:from])
      end
    @to =
      if params[:to].nil? || params[:to].empty?
        @from + 6
      else
        Date.parse(params[:to])
      end
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
  def card_classes(schedule)
    return 'shadow-lg border rounded px-6 py-4 mb-2 bg-red-50' if schedule.has_debut_food

    'shadow-lg border rounded px-6 py-4 mb-2'
  end

  JAPANESE_WDAY = %w[日 月 火 水 木 金 土].freeze

  def view_date(date)
    date = Date.parse(date) if date.is_a?(String)
    date.strftime("%Y年%m月%d日（#{JAPANESE_WDAY[date.wday]}）")
  end
end

app/views/schedules/_form.html.erb
<%= form_with(model: schedule, class: "contents") do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
        <% schedule.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :date %>
    <%= form.date_field :date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/schedules/_schedule.html.erb
<div id="<%= dom_id schedule %>" class="<%= card_classes(schedule) %>">
  <p>
    <%= view_date(schedule.date) %>
  </p>

  <p>
    <strong><%= "#{schedule.meal.ordinal_number}回食(#{schedule.meal.meal_foods.map { |mf| "#{mf.food.name}#{mf.amount}" }.join(' ')})" %></strong>
  </p>

  <% if schedule.has_debut_food %>
    <p>
      初めて食べる食材があります
    </p>
  <% end %>
</div>

app/views/schedules/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing schedule</h1>

  <%= render "form", schedule: @schedule %>

  <%= link_to "Show this schedule", @schedule, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to schedules", schedules_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/schedules/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-teal-50 mb-5 text-teal-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% elsif alert.present? %>
    <p class="py-2 px-3 bg-rose-50 mb-5 text-rose-500 font-medium rounded-lg inline-block" id="alert"><%= alert %></p>
  <% end %>

  <div class ="flex justify-between mb-8">
    <div>
      <h2 class="text-xl font-sans">スケジュール</h2>
    </div>
    <button data-modal-target="defaultModal" data-modal-toggle="defaultModal" class="shadow-lg bg-rose-500 shadow-rose-500/50 hover:bg-rose-400 text-white rounded px-4 py-2" type="button">
      再計算
    </button>
  </div>

<!-- Recalculate modal -->
<div id="defaultModal" tabindex="-1" aria-hidden="true" class="flex justify-center drop-shadow-2xl fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-modal md:h-full">
  <div class="relative w-full h-full max-w-4xl md:h-auto">
    <!-- Modal content -->
    <div class="relative bg-white rounded-lg shadow">
      <!-- Modal header -->
      <div class="flex items-start justify-between p-4 border-b rounded-t">
        <h3 class="text-xl font-semibold text-gray-900">
          スケジュールの再計算
        </h3>
        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" data-modal-hide="defaultModal">
          <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
          <span class="sr-only">Close modal</span>
        </button>
      </div>
      <!-- Modal body -->
      <div class="p-6 space-y-6">
        <p class="text-base leading-relaxed text-gray-500">
          テンプレートをもとに、スケジュールの日付を再計算します。
        </p>
        <p class="text-base leading-relaxed text-gray-500">
          「初めて食べる食材」が日曜・祝日・カスタム休日に重なった場合、直前のスケジュールが繰り返されます。
        </p>
        <p class="text-base leading-relaxed text-gray-500">
          指定した「テンプレートのDay」より前のスケジュールは保持されます。
        </p>
        <p class="text-base leading-relaxed text-gray-500">
          指定した「テンプレートのDay」以降のスケジュールは削除され、新規スケジュールが作成されます。
        </p>
      </div>
      <!-- Modal footer -->
      <%= form_tag recalculate_schedules_path, multipart: true do %>
        <div class="md:flex justify-between p-6 space-x-2 border-t border-gray-200 rounded-b">
          <div>
            <span>テンプレートのDay</span>
            <%= number_field_tag :day, 1, min: 1, class: "w-16 shadow appearance-none border rounded py-2 px-2 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
            <span>を</span>
            <%= date_field_tag :start_date, Date.today, class: "shadow appearance-none border rounded py-2 px-2 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
            <span>に合わせてスケジュールを再計算</span>
          </div>
          <button class="shadow-lg bg-rose-500 shadow-rose-500/50 hover:bg-rose-400 text-white rounded px-4 py-2">
            <%= submit_tag "実行", class: "cursor-pointer" %>
          </button>
        </div>
      <% end %>
    </div>
  </div>
</div>


  <div id="schedules" class="w-full">
    <div class="mb-8">
      <%= form_tag schedules_path, method: :get do %>
        <label class="w-full block">
          検索期間
        </label>
        <div class="flex items-center gap-2">
        <%= date_field_tag :from, @from, class: "shadow appearance-none border rounded py-2 px-2 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
        <%= date_field_tag :to, @to, class: "shadow appearance-none border rounded py-2 px-2 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
        <%= button_tag type: "submit", class: "shadow-lg bg-sky-500 shadow-sky-500/50 hover:bg-sky-400 text-white rounded px-2 py-2" do %>
          <svg aria-hidden="true" class="w-6 h-6 text-white-500 transition duration-75" fill="none" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z"></path>
          </svg>
        <% end %>
        </div>
      <% end %>
    </div>
    <div class="mb-8">
      <button class="shadow-lg bg-sky-500 shadow-sky-500/50 hover:bg-sky-400 text-white rounded px-4 py-2">
        <%= link_to "この期間に必要な食材", sum_schedules_path(from: @from, to: @to), data: { turbo_frame: 'modal' } %>
      </button>
    </div>
    <%= turbo_frame_tag "modal" %>
    <% @schedules.each do |schedule| %>
      <%= render schedule %>
    <% end %>
  </div>
</div>

app/views/schedules/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New schedule</h1>

  <%= render "form", schedule: @schedule %>

  <%= link_to 'Back to schedules', schedules_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/schedules/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @schedule %>

    <%= link_to 'Edit this schedule', edit_schedule_path(@schedule), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this schedule', schedule_path(@schedule), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to schedules', schedules_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/schedules/sum.html.erb
<%= turbo_frame_tag "modal" do %>
  <%= tag.div data: { controller: "turbo-modal" }, class: "shadow-lg border rounded px-6 py-4 mb-2" do %>
    <div class ="flex justify-between mb-8">
      <div>
        <h3 class="text-lg font-sans"><%= "#{view_date(params[:from])}～#{view_date(params[:to])}"%>に必要な食材</h3>
      </div>
      <%= button_tag data: { action: "turbo-modal#hideModal" }, type: "button" do %>
        <svg aria-hidden="true" class="w-6 h-6 text-gray-500 transition duration-75" fill="currentColor" stroke="currentColor" stroke-width="1.5" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"></path></svg>
      <% end %>
    </div>
    <table class="table-auto border">
      <thead>
        <tr>
          <th class="border px-4 py-2">食材</th>
          <th class="border px-4 py-2">量</th>
        </tr>
      </thead>
      <tbody>
        <% @foods.each do |food| %>
          <tr>
            <td class="border px-4 py-2"><%= "#{food[0]}" %></td>
            <td class="border px-4 py-2"><%= "#{food[1].join(', ')}" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
<% end %>