config/routes.rb
Rails.application.routes.draw do
  resources :schedules do
    collection do
      post :recalculate
      get :sum
    end
  end
  resources :custom_holidays
  root to: 'schedules#index'
  resources :meals do
    collection do
      post :import
    end
  end
  namespace 'api', format: 'json' do
    namespace 'v1' do
      resources :schedules do
        collection do
          get :index
        end
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/custom_holiday.rb
class CustomHoliday < ApplicationRecord
  validates :date, presence: true, uniqueness: { case_sensitive: false }
  validates :description, length: { maximum: 50 }
  def self.include?(date)
    return false if CustomHoliday.find_by(date:).nil?

    true
  end
end

app/controllers/custom_holidays_controller.rb
class CustomHolidaysController < ApplicationController
  before_action :set_custom_holiday, only: %i[show edit update destroy]

  # GET /custom_holidays or /custom_holidays.json
  def index
    @custom_holidays = CustomHoliday.all.order(:date)
  end

  # GET /custom_holidays/1 or /custom_holidays/1.json
  def show; end

  # GET /custom_holidays/new
  def new
    @custom_holiday = CustomHoliday.new
  end

  # GET /custom_holidays/1/edit
  def edit; end

  # POST /custom_holidays or /custom_holidays.json
  def create
    @custom_holiday = CustomHoliday.new(custom_holiday_params)

    respond_to do |format|
      if @custom_holiday.save
        format.html do
          redirect_to custom_holiday_url(@custom_holiday), notice: 'Custom holiday was successfully created.'
        end
        format.json { render :show, status: :created, location: @custom_holiday }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @custom_holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /custom_holidays/1 or /custom_holidays/1.json
  def update
    respond_to do |format|
      if @custom_holiday.update(custom_holiday_params)
        format.html do
          redirect_to custom_holiday_url(@custom_holiday), notice: 'Custom holiday was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @custom_holiday }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @custom_holiday.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /custom_holidays/1 or /custom_holidays/1.json
  def destroy
    @custom_holiday.destroy

    respond_to do |format|
      format.html { redirect_to custom_holidays_url, notice: 'Custom holiday was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_custom_holiday
    @custom_holiday = CustomHoliday.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def custom_holiday_params
    params.require(:custom_holiday).permit(:date, :description)
  end
end

app/helpers/custom_holidays_helper.rb
module CustomHolidaysHelper
end

app/views/custom_holidays/_custom_holiday.html.erb
<div id="<%= dom_id custom_holiday %>">
  <p>
    <%= view_date(custom_holiday.date) %>
  </p>

  <p>
    <%= custom_holiday.description %>
  </p>

</div>

app/views/custom_holidays/_form.html.erb
<%= form_with(model: custom_holiday) do |form| %>
  <% if custom_holiday.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(custom_holiday.errors.count, "error") %> prohibited this custom_holiday from being saved:</h2>

      <ul>
        <% custom_holiday.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date, class: "shadow appearance-none border rounded py-2 px-2 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description, class: "shadow appearance-none border rounded py-2 px-2 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div>
    <button class="shadow-lg bg-sky-500 shadow-sky-500/50 hover:bg-sky-400 text-white rounded px-4 py-2">
      <%= form.submit %>
    </button>
  </div>
<% end %>

app/views/custom_holidays/edit.html.erb
<div class ="flex justify-between mb-8">
  <div>
    <h2 class="text-xl font-sans">カスタム休日　編集</h2>
  </div>
</div>

<%= render "form", custom_holiday: @custom_holiday %>

<br>

<div>
  <button class="shadow-lg bg-slate-500 shadow-slate-500/50 hover:bg-slate-400 text-white rounded px-4 py-2">
    <%= link_to "戻る", custom_holidays_path %>
  </button>
</div>

app/views/custom_holidays/index.html.erb
<p style="color: green"><%= notice %></p>

<div class ="flex justify-between mb-8">
  <div>
    <h2 class="text-xl font-sans">カスタム休日</h2>
  </div>
  <div>
    <button class="shadow-lg bg-sky-500 shadow-sky-500/50 hover:bg-sky-400 text-white rounded px-4 py-2">
      <%= link_to "追加", new_custom_holiday_path %>
    </button>
  </div>
</div>

<div id="custom_holidays">
  <% @custom_holidays.each do |custom_holiday| %>
    <div class="flex justify-between shadow-lg border rounded px-6 py-4 mb-2">
      <%= render custom_holiday %>
      <div class="md:flex justify-center gap-4">
        <button class="shadow-lg bg-teal-500 shadow-teal-500/50 hover:bg-teal-400 text-white rounded px-4 py-2 h-10">
          <%= link_to "編集", edit_custom_holiday_path(custom_holiday) %>
        </button>
        <%= button_to "削除", custom_holiday, method: :delete, class: "shadow-lg bg-rose-500 shadow-rose-500/50 hover:bg-rose-400 text-white rounded px-4 py-2 h-10" %>
      </div>
    </div>
  <% end %>
</div>

app/views/custom_holidays/new.html.erb
<div class ="flex justify-between mb-8">
  <div>
    <h2 class="text-xl font-sans">カスタム休日　追加</h2>
  </div>
</div>

<%= render "form", custom_holiday: @custom_holiday %>

<br>

<div>
  <button class="shadow-lg bg-slate-500 shadow-slate-500/50 hover:bg-slate-400 text-white rounded px-4 py-2">
    <%= link_to "戻る", custom_holidays_path %>
  </button>
</div>

app/views/custom_holidays/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @custom_holiday %>

<div>
  <%= link_to "Edit this custom holiday", edit_custom_holiday_path(@custom_holiday) %> |
  <%= link_to "Back to custom holidays", custom_holidays_path %>

  <%= button_to "Destroy this custom holiday", @custom_holiday, method: :delete %>
</div>