config/routes.rb
Rails.application.routes.draw do
  resources :schedules do
    collection do
      post :recalculate
      get :sum
    end
  end
  resources :custom_holidays
  root to: 'schedules#index'
  resources :meals do
    collection do
      post :import
    end
  end
  namespace 'api', format: 'json' do
    namespace 'v1' do
      resources :schedules do
        collection do
          get :index
        end
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/meal.rb
class Meal < ApplicationRecord
  has_many :schedules
  has_many :meal_foods
  has_many :foods, through: :meal_foods

  validates :day, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :ordinal_number, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

  def debut_food?
    meal_foods.inject(false) { |result, mf| result || mf.debut }
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: %i[show edit update destroy]

  # GET /meals or /meals.json
  def index
    @meals = Meal.all.includes(:foods)
  end

  # GET /meals/1 or /meals/1.json
  def show; end

  # GET /meals/new
  def new
    @meal = Meal.new
  end

  # GET /meals/1/edit
  def edit; end

  # POST /meals or /meals.json
  def create
    @meal = Meal.new(meal_params)

    respond_to do |format|
      if @meal.save
        format.html { redirect_to meal_url(@meal), notice: 'Meal was successfully created.' }
        format.json { render :show, status: :created, location: @meal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meals/1 or /meals/1.json
  def update
    respond_to do |format|
      if @meal.update(meal_params)
        format.html { redirect_to meal_url(@meal), notice: 'Meal was successfully updated.' }
        format.json { render :show, status: :ok, location: @meal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1 or /meals/1.json
  def destroy
    @meal.destroy

    respond_to do |format|
      format.html { redirect_to meals_url, notice: 'Meal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /meals/import
  def import
    ImportMealTemplate.call(file_path: params[:file].path)
    RecalculateSchedule.call(day: '1', start_date: params[:start_date])
    redirect_to root_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_meal
    @meal = Meal.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def meal_params
    params.require(:meal).permit(:day, :ordinal_number)
  end
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/meals/_form.html.erb
<%= form_with(model: meal) do |form| %>
  <% if meal.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
        <% meal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :day, style: "display: block" %>
    <%= form.number_field :day %>
  </div>

  <div>
    <%= form.label :ordinal_number, style: "display: block" %>
    <%= form.number_field :ordinal_number %>
  </div>

  <button class="shadow-lg bg-sky-500 shadow-sky-500/50 hover:bg-sky-400 text-white rounded px-4 py-2">
    <%= form.submit %>
  </button>
<% end %>

app/views/meals/_meal.html.erb
<div id="<%= dom_id meal %>">
  <p>
    Day:
    <%= meal.day %>
  </p>

  <p>
    <strong><%= "#{meal.ordinal_number}回食(#{meal.meal_foods.map { |mf| "#{mf.food.name}#{mf.amount}" }.join(' ')})" %></strong>
  </p>

  <% if meal.debut_food? %>
    <p>
      初めて食べる食材があります
    </p>
  <% end %>

</div>

app/views/meals/edit.html.erb
<h1>Editing meal</h1>

<%= render "form", meal: @meal %>

<br>

<div>
  <%= link_to "Show this meal", @meal %> |
  <%= link_to "Back to meals", meals_path %>
</div>

app/views/meals/index.html.erb
<p style="color: green"><%= notice %></p>

<div class ="flex justify-between mb-8">
  <div>
    <h2 class="text-xl font-sans">テンプレート</h2>
  </div>
  <div>
    <button data-modal-target="defaultModal" data-modal-toggle="defaultModal" class="shadow-lg bg-rose-500 shadow-rose-500/50 hover:bg-rose-400 text-white rounded px-4 py-2" type="button">
      インポート
    </button>
  </div>
</div>

<!-- Recalculate modal -->
<div id="defaultModal" tabindex="-1" aria-hidden="true" class="flex justify-center drop-shadow-2xl fixed top-0 left-0 right-0 z-50 hidden w-full p-4 overflow-x-hidden overflow-y-auto md:inset-0 h-modal md:h-full">
  <div class="relative w-full h-full max-w-4xl md:h-auto">
    <!-- Modal content -->
    <div class="relative bg-white rounded-lg shadow">
      <!-- Modal header -->
      <div class="flex items-start justify-between p-4 border-b rounded-t">
        <h3 class="text-xl font-semibold text-gray-900">
          スケジュールテンプレートのインポート
        </h3>
        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" data-modal-hide="defaultModal">
          <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
          <span class="sr-only">Close modal</span>
        </button>
      </div>
      <!-- Modal body -->
      <div class="p-6 space-y-6">
        <p class="text-base leading-relaxed text-gray-500">
          CSVからテンプレートをインポートします。
        </p>
        <p class="text-base leading-relaxed text-gray-500">
          登録されているテンプレート・スケジュールは全て削除されます。
        </p>
        <p class="text-base leading-relaxed text-gray-500">
          テンプレートのインポート完了後、「開始日」に指定した日付を始点にスケジュールが自動で設定されます。
        </p>
      </div>
      <!-- Modal footer -->
      <%= form_tag import_meals_path, multipart: true do %>
        <div class="md:flex justify-between p-6 space-x-2 border-t border-gray-200 rounded-b">
          <div class="flex justify-left items-center">
            <%= file_field_tag :file, class: "block text-sm text-slate-500 file:mr-4 file:py-2 file:px-4 file:rounded file:border-0 file:text-sm file:font-semibold file:bg-sky-50 file:text-sky-700 hover:file:bg-sky-100" %>
            <span>開始日</span>
            <%= date_field_tag :start_date, Date.today, class: "shadow appearance-none border rounded py-2 px-2 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
          </div>
          <button class="shadow-lg bg-rose-500 shadow-rose-500/50 hover:bg-rose-400 text-white rounded px-4 py-2">
            <%= submit_tag "実行", class: "cursor-pointer" %>
          </button>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div id="meals" class="w-full">
  <% @meals.each do |meal| %>
    <div class="shadow-lg border rounded px-6 py-4 mb-2">
      <%= render meal %>
    </div>
  <% end %>
</div>

app/views/meals/new.html.erb
<h1>New meal</h1>

<%= render "form", meal: @meal %>

<br>

<button class="shadow-lg bg-sky-500 shadow-sky-500/50 hover:bg-sky-400 text-white rounded px-4 py-2">
  <%= link_to "Back to meals", meals_path %>
</button>

app/views/meals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @meal %>

<div>
  <%= link_to "Edit this meal", edit_meal_path(@meal) %> |
  <%= link_to "Back to meals", meals_path %>

  <%= button_to "Destroy this meal", @meal, method: :delete %>
</div>